declare -r DB_URL="http://localhost:8889/bigdata/namespace/kb/sparql"
declare -r SRC_PATH="/home/deras/Powergrid-Models/platform/"
declare -r CIMHUB_PATH="../../CIMHub/target/libs/*:../../CIMHub/target/cimhub-0.0.1-SNAPSHOT.jar"
declare -r CIMHUB_PROG="gov.pnnl.gridappsd.cimhub.CIMImporter"
declare -r CIMHUB_UTILS="./"
