Feature: GO

#  @notdone @unrevised
#  Scenario: GO01: The GO SHOULD have awareness of EDM grid model states.
#    Given A ME simulation is running, in which a set of measurements has already been provided to the measurement processor. Per-timestep actions are being performed according to the timekeeper class.
#    When The timekeeper uses the measurement processor’s accessor method to send grid states to the GO class.
#    Then The GO prints the grid states to the terminal using a test function.
#
#  @notdone @unrevised
#  Scenario: GO02: The GO SHOULD determine an appropriate grid service based on system state data from the EDM.
#    Given A test is being executed.
#    When Grid states are sent to the GO class.
#    Then Grid service requests are generated by the GO class and printed to the terminal via a test function.

  @notdone @tpme3
  Scenario: GO03: The GO SHALL have an API between itself and the DERMS.
    Given Grid services need to be dispatched
    When The GO dispatches a grid service request
    Then The GO should output an XML file available for use by the GSP.

  @notdone @tpme3 # Same as GO03
  Scenario: GO04: The GO SHALL be able to request grid services from the DERMS.
    Given Grid services need to be dispatched
    When The GO dispatches a grid service request
    Then The GO should output an XML file available for use by the GSP.

  @tpme1
  Scenario: GO05: The GO SHALL provide a method to permit the TE to request grid services.
    Given A manually posted service input file is available
    When The function to manually post a service is called
    Then A GOPostedService object should be instantiated


#  @notdone @unrevised
#  Scenario: GO06: The GO SHOULD provide feedback data to the DERMS.
#    Given A ME test is underway. GO-GSP communications are established.
#    When Feedback data is provided to the GO sensor class by the measurement processor.
#    Then Feedback data is provided to the DERMS by the GO API class within a formatted message.
#
#
#  @notdone @unrevised
#  Scenario: GO07: The GO MAY alert the MC if it loses communication with a DERMS.
#    Given The ME is performing a test involving an open connection between the GO and DERMS.
#    When The connection between the GO and DERMS is broken.
#    Then A message is printed to the terminal informing the TE about the broken connection.



